# Online AWS environment configuration file

# Host configuration
host: "https://aws-online-api.example.com"

# Timeout configuration
timeout: 60
retry_count: 3

# Default request headers
default_headers:
  Content-Type: "application/json"
  Accept: "application/json"
  User-Agent: "PTE/1.0"

# Database configuration
database:
  mysql:
    host: "aws-online-mysql.example.com"
    port: 3306
    username: "online_user"
    password: "online_password"
    database: "online_db"
    charset: "utf8mb4"
    pool_size: 20
    max_overflow: 30
    pool_timeout: 60
    pool_recycle: 3600
    description: "Online AWS MySQL database"

# Environment configuration
environments:
  # Online production environment
  prod:
    timeout: 120
    retry_count: 3
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      Referer: "https://online.example.com"
      Authorization: "Bearer prod-token"
    description: "Online production environment"
    
  # Online feature 1 pre-release environment
  pre_fea1:
    timeout: 60
    retry_count: 5
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      Referer: "https://pre-fea1.example.com"
      Authorization: "Bearer pre-fea1-token"
    description: "Online feature 1 pre-release environment"
    
  # Online feature 2 pre-release environment
  pre_fea2:
    timeout: 60
    retry_count: 5
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      Referer: "https://pre-fea2.example.com"
      Authorization: "Bearer pre-fea2-token"
    description: "Online feature 2 pre-release environment"
    
  # Online pre-staging environment
  pre_staging:
    timeout: 60
    retry_count: 5
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      Referer: "https://pre-staging.example.com"
      Authorization: "Bearer pre-staging-token"
    description: "Online pre-staging environment"

# Test configuration
test_config:
  # Test data directory
  test_data_dir: "data"
  
  # Test report directory
  test_report_dir: "reports"
  
  # Test log directory
  test_log_dir: "logs"
  
  # Default test markers
  default_markers:
    - "unit"
    - "integration"
    - "api"
    - "smoke"
    - "regression"
    - "online"
    - "aws"
