# Offline AWS environment configuration file

# Host configuration
host: "http://aws-offline-api.example.com"

# Timeout configuration
timeout: 30
retry_count: 3

# Default request headers
default_headers:
  Content-Type: "application/json"
  Accept: "application/json"
  User-Agent: "Universal-Test-Framework/1.0"

# Database configuration
database:
  mysql:
    host: "aws-offline-mysql.example.com"
    port: 3306
    username: "offline_user"
    password: "offline_password"
    database: "offline_db"
    charset: "utf8mb4"
    pool_size: 10
    max_overflow: 20
    pool_timeout: 30
    pool_recycle: 3600
    description: "Offline AWS MySQL database"

# Environment configuration
environments:
  # Offline production environment
  prod:
    timeout: 30
    retry_count: 3
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      Referer: "http://offline.example.com"
    description: "Offline production environment"
    
  # Offline feature 1 development environment
  dev_fea1:
    timeout: 30
    retry_count: 3
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      Referer: "http://dev-fea1.example.com"
    description: "Offline feature 1 development environment"
    
  # Offline CI environment
  dev_ci:
    timeout: 30
    retry_count: 3
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      Referer: "http://dev-ci.example.com"
    description: "Offline CI environment"
    
  # Offline test environment
  dev_test:
    timeout: 30
    retry_count: 3
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      Referer: "http://dev-test.example.com"
    description: "Offline test environment"

# Test configuration
test_config:
  # Test data directory
  test_data_dir: "data"
  
  # Test report directory
  test_report_dir: "reports"
  
  # Test log directory
  test_log_dir: "logs"
  
  # Default test markers
  default_markers:
    - "unit"
    - "integration"
    - "api"
    - "smoke"
    - "regression"
    - "offline"
    - "aws"
