# Common configuration file - includes logging, reporting and other common configurations

# Logging configuration
logging:
  # Whether to enable file logging output
  enable_file_logging: true
  
  # Log file configuration
  file:
    # Log file directory (relative to project root)
    directory: "logs"
    
    # Log filename format (supports time variables and test case information)
    # Available variables: {date}, {time}, {datetime}, {level}, {testcase}, {logid}
    # {date}: Date in YYYYMMDD format
    # {time}: Time in HHMMSS format
    # {datetime}: Date and time in YYYYMMDD_HHMMSS format
    # {testcase}: Test case name (automatically extracted)
    # {logid}: Current LogID (automatically filled)
    filename_format: "pte_{datetime}_{testcase}_{logid}_{level}.log"
    
    # Log level (DEBUG, INFO, WARNING, ERROR)
    level: "INFO"
    
    # Log format
    format: "[{timestamp}] [{level}] [{logid}] [{caller}] {message}"
    
    # Whether to split log files by date
    rotate_by_date: true
    
    # Whether to output separate files by log level
    separate_by_level: false
    
    # Log file retention days (0 means no deletion)
    retention_days: 30
    
    # Maximum log file size (MB, 0 means no limit)
    max_size_mb: 100
    
    # Whether to enable log compression
    enable_compression: false
  
  # Console output configuration
  console:
    # Whether to enable console output
    enabled: true
    
    # Console log level
    level: "ERROR"
    
    # Console log format
    format: "[{timestamp}] [{level}] [{logid}] [{caller}] {message}"
  
  # Allure report configuration
  allure:
    # Whether to enable Allure log output
    enabled: true
    
    # Allure log level
    level: "INFO"
    
    # Whether to show detailed data in Allure
    show_detailed_data: true

# Reporting configuration
reporting:
  # Allure report configuration
  allure:
    # Report output directory
    output_dir: "reports/allure"
    
    # Whether to auto-generate reports
    auto_generate: true
    
    # Report title
    title: "PTE Test Report"
  
  # Coverage report configuration
  coverage:
    # Coverage report output directory
    output_dir: "reports/coverage"
    
    # Whether to generate HTML reports
    generate_html: true
    
    # Whether to generate XML reports
    generate_xml: true

# Test configuration
test:
  # Default timeout (seconds)
  default_timeout: 30
  
  # Default retry count
  default_retry_count: 3
  
  # Parallel test configuration
  parallel:
    # Whether to enable parallel testing
    enabled: false
    
    # Number of parallel processes
    workers: 2
    
    # Parallel mode (processes, threads)
    mode: "processes"
  
  # Data-driven configuration
  data_driven:
    # Test data directory
    data_dir: "data"
    
    # Whether to enable data-driven testing
    enabled: true

# Environment configuration
environment:
  # Default environment
  default: "local"
  
  # Available environments
  available:
    - "local"
    - "dev"
    - "test"
    - "staging"
    - "prod"
